"""empty message

Revision ID: 24f0085848bb
Revises: ce2cb9617b71
Create Date: 2018-07-23 14:31:24.500240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24f0085848bb'
down_revision = 'ce2cb9617b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psn_category', sa.Column('game_id', sa.JSON(), nullable=False))
    op.drop_column('psn_category', 'gameItem')
    op.add_column('psn_game', sa.Column('game_id', sa.String(), nullable=True))
    op.add_column('psn_game', sa.Column('game_title', sa.String(), nullable=True))
    op.add_column('psn_game', sa.Column('game_type', sa.String(), nullable=True))
    op.add_column('psn_game', sa.Column('game_url', sa.String(), nullable=True))
    op.add_column('psn_game', sa.Column('highest_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('psn_game', sa.Column('lowest_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('psn_game', sa.Column('plus_lowest_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.create_unique_constraint(None, 'psn_game', ['game_id'])
    op.drop_column('psn_game', 'title_name')
    op.drop_column('psn_game', 'title_type')
    op.drop_column('psn_game', 'title_url')
    op.create_unique_constraint(None, 'psn_price_history', ['game_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'psn_price_history', type_='unique')
    op.add_column('psn_game', sa.Column('title_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('psn_game', sa.Column('title_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('psn_game', sa.Column('title_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'psn_game', type_='unique')
    op.drop_column('psn_game', 'plus_lowest_price')
    op.drop_column('psn_game', 'lowest_price')
    op.drop_column('psn_game', 'highest_price')
    op.drop_column('psn_game', 'game_url')
    op.drop_column('psn_game', 'game_type')
    op.drop_column('psn_game', 'game_title')
    op.drop_column('psn_game', 'game_id')
    op.add_column('psn_category', sa.Column('gameItem', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('psn_category', 'game_id')
    # ### end Alembic commands ###
