"""empty message

Revision ID: 2b66da83cdce
Revises: 476f1d558a77
Create Date: 2018-07-23 17:29:05.004772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b66da83cdce'
down_revision = '476f1d558a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psn_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_url', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('game_id', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psn_category_quick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_url', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('gameItem', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psn_category_quick')
    op.drop_table('psn_category')
    # ### end Alembic commands ###
