"""empty message

Revision ID: 2f9903440862
Revises: 9d7a920c8bd2
Create Date: 2018-07-23 14:38:05.953124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f9903440862'
down_revision = '9d7a920c8bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psn_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('game_title', sa.String(), nullable=True),
    sa.Column('chartPrices', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('chartBonusPrices', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psn_price_history')
    # ### end Alembic commands ###
