"""empty message

Revision ID: 3973ed0b5f61
Revises: 2f9903440862
Create Date: 2018-07-23 16:13:19.471661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3973ed0b5f61'
down_revision = '2f9903440862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psn_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('game_title', sa.String(), nullable=True),
    sa.Column('game_type', sa.String(), nullable=True),
    sa.Column('game_url', sa.String(), nullable=True),
    sa.Column('thumb_img_url', sa.String(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('regular_price', sa.String(), nullable=True),
    sa.Column('display_price', sa.String(), nullable=True),
    sa.Column('discount_message', sa.String(), nullable=True),
    sa.Column('plus_price', sa.String(), nullable=True),
    sa.Column('plus_exclusive_price', sa.String(), nullable=True),
    sa.Column('highest_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('lowest_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('plus_lowest_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psn_game')
    # ### end Alembic commands ###
