"""empty message

Revision ID: 476f1d558a77
Revises: 91632acc035d
Create Date: 2018-07-23 17:15:45.876021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476f1d558a77'
down_revision = '91632acc035d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psn_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_url', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('game_id', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psn_category')
    # ### end Alembic commands ###
