"""empty message

Revision ID: 583606454499
Revises: 4802e52914d2
Create Date: 2018-07-24 16:30:03.817644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583606454499'
down_revision = '4802e52914d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'psn_price_history', ['game_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'psn_price_history', type_='unique')
    # ### end Alembic commands ###
