"""empty message

Revision ID: 91632acc035d
Revises: 3973ed0b5f61
Create Date: 2018-07-23 17:15:13.343242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91632acc035d'
down_revision = '3973ed0b5f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psn_category_quick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_url', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('gameItem', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psn_category_quick')
    # ### end Alembic commands ###
