"""empty message

Revision ID: 9d7a920c8bd2
Revises: 0e9f5494747b
Create Date: 2018-07-23 14:36:53.141775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d7a920c8bd2'
down_revision = '0e9f5494747b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psn_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('game_title', sa.String(), nullable=True),
    sa.Column('chartPrices', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('chartBonusPrices', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psn_price_history')
    # ### end Alembic commands ###
