"""empty message

Revision ID: b1d29ec30d3f
Revises: caced45ad29b
Create Date: 2018-08-20 00:13:38.092593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d29ec30d3f'
down_revision = 'caced45ad29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psn_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_url', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psn_category')
    # ### end Alembic commands ###
