"""empty message

Revision ID: caced45ad29b
Revises: 
Create Date: 2018-08-20 00:10:08.543429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'caced45ad29b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psn_category_quick')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psn_category_quick',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gameItem', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='psn_category_quick_pkey')
    )
    # ### end Alembic commands ###
