"""empty message

Revision ID: d8ec17b8969f
Revises: b1d29ec30d3f
Create Date: 2018-08-25 17:36:36.155515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ec17b8969f'
down_revision = 'b1d29ec30d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psn_banner', sa.Column('banner_background_url', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psn_banner', 'banner_background_url')
    # ### end Alembic commands ###
