"""empty message

Revision ID: dac6c81f0447
Revises: 583606454499
Create Date: 2018-07-25 14:49:56.756570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac6c81f0447'
down_revision = '583606454499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psn_game', 'highest_price')
    op.drop_column('psn_game', 'plus_lowest_price')
    op.drop_column('psn_game', 'lowest_price')
    op.add_column('psn_price_history', sa.Column('highest_price', sa.Float(precision=10, asdecimal=2), nullable=True))
    op.add_column('psn_price_history', sa.Column('lowest_price', sa.Float(precision=10, asdecimal=2), nullable=True))
    op.add_column('psn_price_history', sa.Column('plus_lowest_price', sa.Float(precision=10, asdecimal=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psn_price_history', 'plus_lowest_price')
    op.drop_column('psn_price_history', 'lowest_price')
    op.drop_column('psn_price_history', 'highest_price')
    op.add_column('psn_game', sa.Column('lowest_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('psn_game', sa.Column('plus_lowest_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('psn_game', sa.Column('highest_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
